name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} using conda
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniconda-version: latest
            channels: conda-forge
            activate-environment: ci_env
            python-version: ${{ matrix.python-version }}

      - name: Install environment
        shell: bash -l {0}
        run: |
            conda env update -f environment.yml -n ci_env

      - name: Run examples Day 1
        shell: bash -l {0}
        run: |
          conda run -n ci_env python -m compas
          conda run -n ci_env python day1/02/001_box.py
